"""added new Column in Note model

Revision ID: 3d274fb206df
Revises: 20685f218f7a
Create Date: 2026-03-21 19:18:02.489566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d274fb206df'
down_revision = '20685f218f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'created_at')
    # ### end Alembic commands ###
